version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: "il-central-1"
    ACCOUNT_ID: "923337630273"
    ECR_APP_REPO: "project1-app"
    ECR_NGINX_REPO: "project1-nginx"

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - aws --version
      - docker --version
      - echo "Login to ECR"
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - COMMIT_SHA="$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION:-}" | cut -c 1-7)"
      - IMAGE_TAG="${COMMIT_SHA:-manual}"
      - APP_IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_APP_REPO:$IMAGE_TAG"
      - NGINX_IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_NGINX_REPO:$IMAGE_TAG"
      - echo "IMAGE_TAG=$IMAGE_TAG"
  build:
    commands:
      - echo "Build app (inject APP_VERSION=$IMAGE_TAG)"
      - docker build -f app/Dockerfile -t "$ECR_APP_REPO:$IMAGE_TAG" app --build-arg APP_VERSION="$IMAGE_TAG"
      - docker tag "$ECR_APP_REPO:$IMAGE_TAG" "$APP_IMAGE_URI"
      - echo "Build nginx"
      - docker build -f nginx/Dockerfile -t "$ECR_NGINX_REPO:$IMAGE_TAG" nginx
      - docker tag "$ECR_NGINX_REPO:$IMAGE_TAG" "$NGINX_IMAGE_URI"
  post_build:
    commands:
      - echo "Push to ECR"
      - docker tag "$APP_IMAGE_URI" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_APP_REPO:latest"
      - docker tag "$NGINX_IMAGE_URI" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_NGINX_REPO:latest"
      - docker push "$APP_IMAGE_URI"
      - docker push "$NGINX_IMAGE_URI"
      - docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_APP_REPO:latest"
      - docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_NGINX_REPO:latest"
      - echo "Create imagedefinitions.json"
      - printf '[{"name":"nginx","imageUri":"%s"},{"name":"app","imageUri":"%s"}]\n' "$NGINX_IMAGE_URI" "$APP_IMAGE_URI" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

